### ISSUE TITLE
js2 crashes with simple input

### ISSUE THREAD

**Issue by mbandsmer** [Xuth/js2#1]
Awesome program - thanks for sharing it!  However, this simple input puzzle file (attached) causes js2 to crash.  Other, more complicted, input files I have tried have all worked.

Program output:
```
C:\dev\mydev\klotskiSolver\js2-master>js2 puz-nbickford-4.txt
js2 (formerly jim'slide)
version 1.5
copyright Jim Leonard (Xuth) 1999 - 2018
this code may be distributed under the BSD 4-Clause License included in the file LICENSE
numPiece - 4
numSpace - 6
numType - 4
bitsPerType - 3
compressedPuzSize - 4
xsize - 6
ysize - 6
# # # # # #
#     1 1 #
# 2 2 1   #
#   3 4   #
# 3 3 4   #
# # # # # #

# # # # # #
#     1 1 #
# 2 2 1   #
#     3 4 #
#   3 3 4 #
# # # # # #

starting thread 0
Starting caching thread
level: 1 positions: 1 at time: 0
level: 2 positions: 4 at time: 0
Can't place a piece in uncompress()
assertion "0" failed: file "js2.cpp", line 100, function: void test(int, const char*)
      0 [js2] js2 311 cygwin_exception::open_stackdumpfile: Dumping stack trace to js2.exe.stackdump

C:\dev\mydev\klotskiSolver\js2-master>
```
Side note: I had to change the makefile to add  -D_GNU_SOURCE  to the CPPFLAGS, otherwise g++ complained about strdupa.
[puz-nbickford-4.txt](https://github.com/Xuth/js2/files/4646843/puz-nbickford-4.txt)

**Comment by Xuth** [comment]
This is more a bug in the documentation (followed by a not so great input parser that should be able to handle the issue).  I need to do better piece normalizing on input and make the input more friendly/tolerant.

Without going through the code again to figure out the minimum constraints it expects I'll give you a set of constraints that might be more constraining than necessary but will definitely work.  Set (0,0) as the left most block of the upper row of a piece and set that as the first square defined in your piece definition.  It's ok for your x values to be negative in subsequent rows in the piece definition.

specifically change

> piece: 3 (0, 1)(1, 0)(1, 1)

to 

> piece: 3(0,0)(-1,1)(0,1)

and change

> put: 3 (0, 2) '3'

to

> put: 3 (1,2) '3'

I _think_ it's merely necessary that (0,0) be a part of the piece but I'm not certain of that.

I'm sorry that this is more confusing than it should be.

**Comment by mbandsmer** [comment]
Thanks - that workaround is what was needed.
